### ISSUE TITLE
Add communities list

### ISSUE THREAD

**Issue by keon** [4337Mafia/awesome-account-abstraction#17]
The idea is to add a list of group chats, threads, and communities where 4337 talks are happening. Please comment below if you know any of:

discord channels
Twitter
TG chats

**Comment by randomishwalk** [comment]
Surprised we didn't have this already! Also, what do you think about generalizing this out to "account abstraction" as a broad topic area instead of focusing purely on ERC-4337?

**Telegram**
- 4337 mafia (product and application)
- 4337 fan club (EIP, research, security)

**Twitter**
- 4337mafia

**Discord**
- Infinitism
- Ethereum wallets

**Research and technical forums**
- Fellowship of Ethereum Magicians
- ETH Research
- Ethereum StackExchange

**Comment by jzaki** [comment]
For completeness could we add the [blswallet](blswallet.org) project?
Abstraction of verification and payment via smart contracts (alpha built prior to 4337 article). V2 will be 4337 compatible.

**Discord**
- [Web3Well](https://discord.gg/hGDmAhcRyz) (blswallet integrations)

**Comment by randomishwalk** [comment]
> For completeness could we add the [blswallet](blswallet.org) project? Abstraction of verification and payment via smart contracts (alpha built prior to 4337 article). V2 will be 4337 compatible.
> 
> **Discord**
> 
> * [Web3Well](https://discord.gg/hGDmAhcRyz) (blswallet integrations)

Sure! Good by me to add the Discord to this community list.

@jzaki - what do you think about separately adding [blswallet](https://github.com/4337Mafia/awesome-account-abstraction/issues/blswallet.org) to the [project list](https://github.com/4337Mafia/awesome-account-abstraction#projects)?

Just want to keep things organized! let us know

**Comment by keon** [comment]
I'll close this issue as the communities mentioned above are added to the list. 
Please open a new issue to add a new community.
